name: mobile
description: "Brain Tumor Detection - AI Powered"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  http: ^1.6.0
  path: ^1.9.0
  google_fonts: ^6.3.0
  image: ^4.1.3
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
